<a href="https://colab.research.google.com/github/kty3452/ML-Class/blob/main/week2/wisdomDatasetCNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task
"/content/drive/MyDrive/ML_Class/WISDM_ar_v1.1_raw.txt" 파일을 사용하여 CNN 방식으로 활동 인식을 수행합니다.

## 데이터 로드 및 탐색

### Subtask:
지정된 파일에서 데이터를 로드하고 구조 및 내용을 검사합니다.


**Reasoning**:
Load the data from the specified file into a pandas DataFrame, displaying the first few rows, and showing the info and description of the DataFrame, as well as the value counts of the 'activity' column.



In [38]:
import pandas as pd

# Load the data into a pandas DataFrame
# Data is space-separated and has no header.
# Using specified column names: 'user', 'activity', 'timestamp', 'x', 'y', 'z'
# 데이터를 pandas DataFrame으로 로드합니다.
# 데이터는 공백으로 구분되어 있으며 헤더가 없습니다.
# 지정된 열 이름 사용: 'user', 'activity', 'timestamp', 'x', 'y', 'z'
df_raw = pd.read_csv(
    '/content/drive/MyDrive/ML_Class/WISDM_ar_v1.1_raw.txt',
    sep=' ',
    header=None,
    names=['user', 'activity', 'timestamp', 'x', 'y', 'z']
)

# Display the first 5 rows to verify data loading
# 데이터 로드를 확인하기 위해 처음 5개 행을 표시합니다.
print("First 5 rows of the DataFrame:")
display(df_raw.head())

# Print the DataFrame's info to check column types and non-null counts
# 열 유형 및 null이 아닌 개수를 확인하기 위해 DataFrame 정보 출력
print("\nDataFrame Info:")
df_raw.info()

# Print descriptive statistics to understand the distribution of numerical columns
# 숫자 열의 분포를 이해하기 위해 기술 통계 출력
print("\nDataFrame Description:")
display(df_raw.describe())

# Check unique activity types and their counts
# 고유 활동 유형 및 개수 확인
print("\nActivity counts:")
display(df_raw['activity'].value_counts())

First 5 rows of the DataFrame:


user  activity  timestamp   x  \
0  33,Jogging,49105962326000,-0.6946377,12.680544...       NaN        NaN NaN   
1  33,Jogging,49106062271000,5.012288,11.264028,0...       NaN        NaN NaN   
2  33,Jogging,49106112167000,4.903325,10.882658,-...       NaN        NaN NaN   
3  33,Jogging,49106222305000,-0.61291564,18.49643...       NaN        NaN NaN   
4  33,Jogging,49106332290000,-1.1849703,12.108489...       NaN        NaN NaN   

    y   z  
0 NaN NaN  
1 NaN NaN  
2 NaN NaN  
3 NaN NaN  
4 NaN NaN


DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1098204 entries, 0 to 1098203
Data columns (total 6 columns):
 #   Column     Non-Null Count    Dtype  
---  ------     --------------    -----  
 0   user       1098204 non-null  object 
 1   activity   0 non-null        float64
 2   timestamp  0 non-null        float64
 3   x          0 non-null        float64
 4   y          0 non-null        float64
 5   z          0 non-null        float64
dtypes: float64(5), object(1)
memory usage: 50.3+ MB

DataFrame Description:


activity  timestamp    x    y    z
count       0.0        0.0  0.0  0.0  0.0
mean        NaN        NaN  NaN  NaN  NaN
std         NaN        NaN  NaN  NaN  NaN
min         NaN        NaN  NaN  NaN  NaN
25%         NaN        NaN  NaN  NaN  NaN
50%         NaN        NaN  NaN  NaN  NaN
75%         NaN        NaN  NaN  NaN  NaN
max         NaN        NaN  NaN  NaN  NaN


Activity counts:


Series([], Name: count, dtype: int64)

**Reasoning**:
The data was not loaded correctly because the columns were not separated as expected. The first column contains all the data. I need to reload the data using a different separator. It appears the data is comma-separated, and some lines have a semicolon at the end. I will try reading it with a comma separator and handle the potential semicolon at the end of the 'z' column. Then I will re-examine the data as before.



In [39]:
# Reload the data into a pandas DataFrame, this time using comma as a separator.
# Also, explicitly handle the potential semicolon at the end of the 'z' column by using a custom parser.
# 이번에는 쉼표를 구분 기호로 사용하여 데이터를 pandas DataFrame으로 다시 로드합니다.
# 또한 사용자 지정 파서를 사용하여 'z' 열 끝에 있을 수 있는 세미콜론을 명시적으로 처리합니다.
df_raw = pd.read_csv(
    '/content/drive/MyDrive/ML_Class/WISDM_ar_v1.1_raw.txt',
    sep=',',
    header=None,
    names=['user', 'activity', 'timestamp', 'x', 'y', 'z']
)

# Remove the semicolon from the 'z' column if it exists
# 'z' 열에 세미콜론이 있으면 제거합니다.
df_raw['z'] = df_raw['z'].astype(str).str.replace(';', '')

# Convert 'x', 'y', and 'z' columns to numeric, coercing errors to NaN
# 'x', 'y', 'z' 열을 숫자로 변환하고 오류 발생 시 NaN으로 강제 변환합니다.
df_raw['x'] = pd.to_numeric(df_raw['x'], errors='coerce')
df_raw['y'] = pd.to_numeric(df_raw['y'], errors='coerce')
df_raw['z'] = pd.to_numeric(df_raw['z'], errors='coerce')

# Display the first 5 rows to verify data loading
# 데이터 로드를 확인하기 위해 구분 기호 수정 후 처음 5개 행을 표시합니다.
print("First 5 rows of the DataFrame after fixing separator:")
display(df_raw.head())

# Print the DataFrame's info to check column types and non-null counts
# 구분 기호 수정 후 열 유형 및 null이 아닌 개수를 확인하기 위해 DataFrame 정보 출력
print("\nDataFrame Info after fixing separator:")
df_raw.info()

# Print descriptive statistics to understand the distribution of numerical columns
# 구분 기호 수정 후 숫자 열의 분포를 이해하기 위해 기술 통계 출력
print("\nDataFrame Description after fixing separator:")
display(df_raw.describe())

# Check unique activity types and their counts
# 구분 기호 수정 후 고유 활동 유형 및 개수 확인
print("\nActivity counts after fixing separator:")
display(df_raw['activity'].value_counts())

ParserError: Error tokenizing data. C error: Expected 6 fields in line 134634, saw 11


**Reasoning**:
The previous attempt to load the data with a comma separator failed due to a `ParserError`, indicating that some lines do not have the expected number of fields. This suggests that the delimiter might not be consistent throughout the file, or there might be issues with how lines are structured. Given the original `df_raw` showed data concatenated in the first column, it's highly likely the file isn't strictly comma-separated. I will try reading the file line by line and manually parse each line based on the expected structure (user,activity,timestamp,x,y,z). This approach is more robust to inconsistent delimiters or extra fields within lines.



In [40]:
# Manually read and parse the data line by line
# 데이터를 줄 단위로 수동으로 읽고 구문 분석합니다.
data = []
with open('/content/drive/MyDrive/ML_Class/WISDM_ar_v1.1_raw.txt', 'r') as f:
    for line in f:
        # Remove trailing whitespace and the potential semicolon
        # 후행 공백과 있을 수 있는 세미콜론을 제거합니다.
        line = line.strip().replace(';', '')
        # Split the line by comma
        # 쉼표로 줄을 분할합니다.
        parts = line.split(',')
        # Check if the line has the expected number of parts (6)
        # 줄에 예상되는 부분 수(6)가 있는지 확인합니다.
        if len(parts) == 6:
            try:
                # Convert parts to appropriate data types
                # 부분을 적절한 데이터 유형으로 변환합니다.
                user = int(parts[0])
                activity = parts[1]
                timestamp = int(parts[2])
                x = float(parts[3])
                y = float(parts[4])
                z = float(parts[5])
                data.append([user, activity, timestamp, x, y, z])
            except ValueError:
                # Skip lines with incorrect data types
                # 잘못된 데이터 유형의 줄은 건너뜁니다.
                continue
        else:
             # Optionally, print lines that don't have 6 parts to understand the issue
             # 문제를 이해하기 위해 6개 부분이 없는 줄을 선택적으로 출력할 수 있습니다.
             # print(f"Skipping line with unexpected number of fields: {line}")
             continue

# Create a DataFrame from the parsed data
# 구문 분석된 데이터로 DataFrame을 만듭니다.
df_raw = pd.DataFrame(data, columns=['user', 'activity', 'timestamp', 'x', 'y', 'z'])

# Display the first 5 rows to verify data loading
# 수동 구문 분석 후 데이터 로드를 확인하기 위해 처음 5개 행을 표시합니다.
print("First 5 rows of the DataFrame after manual parsing:")
display(df_raw.head())

# Print the DataFrame's info to check column types and non-null counts
# 수동 구문 분석 후 열 유형 및 null이 아닌 개수를 확인하기 위해 DataFrame 정보 출력
print("\nDataFrame Info after manual parsing:")
df_raw.info()

# Print descriptive statistics to understand the distribution of numerical columns
# 수동 구문 분석 후 숫자 열의 분포를 이해하기 위해 기술 통계 출력
print("\nDataFrame Description after manual parsing:")
display(df_raw.describe())

# Check unique activity types and their counts
# 수동 구문 분석 후 고유 활동 유형 및 개수 확인
print("\nActivity counts after manual parsing:")
display(df_raw['activity'].value_counts())

First 5 rows of the DataFrame after manual parsing:


user activity       timestamp         x          y         z
0    33  Jogging  49105962326000 -0.694638  12.680544  0.503953
1    33  Jogging  49106062271000  5.012288  11.264028  0.953424
2    33  Jogging  49106112167000  4.903325  10.882658 -0.081722
3    33  Jogging  49106222305000 -0.612916  18.496431  3.023717
4    33  Jogging  49106332290000 -1.184970  12.108489  7.205164


DataFrame Info after manual parsing:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1086465 entries, 0 to 1086464
Data columns (total 6 columns):
 #   Column     Non-Null Count    Dtype  
---  ------     --------------    -----  
 0   user       1086465 non-null  int64  
 1   activity   1086465 non-null  object 
 2   timestamp  1086465 non-null  int64  
 3   x          1086465 non-null  float64
 4   y          1086465 non-null  float64
 5   z          1086465 non-null  float64
dtypes: float64(3), int64(2), object(1)
memory usage: 49.7+ MB

DataFrame Description after manual parsing:


user     timestamp             x             y             z
count  1.086465e+06  1.086465e+06  1.086465e+06  1.086465e+06  1.086465e+06
mean   1.883756e+01  3.250279e+13  6.641130e-01  7.246045e+00  3.976974e-01
std    1.026681e+01  4.893650e+13  6.876277e+00  6.739789e+00  4.761111e+00
min    1.000000e+00  0.000000e+00 -1.961000e+01 -1.961000e+01 -1.980000e+01
25%    1.000000e+01  1.999712e+12 -2.910000e+00  3.170000e+00 -2.220117e+00
50%    1.900000e+01  9.396203e+12  2.700000e-01  7.930000e+00  0.000000e+00
75%    2.800000e+01  3.509473e+13  4.440000e+00  1.156000e+01  2.720000e+00
max    3.600000e+01  2.093974e+14  1.995000e+01  2.004000e+01  1.961000e+01


Activity counts after manual parsing:


activity
Walking       418393
Jogging       336445
Upstairs      122869
Downstairs    100425
Sitting        59939
Standing       48394
Name: count, dtype: int64

## 데이터 전처리

### Subtask:
CNN 모델에 맞게 데이터를 전처리합니다. 여기에는 누락된 값 처리, 데이터 스케일링, 시계열 데이터를 CNN 입력 형식에 맞게 재구성하는 작업이 포함될 수 있습니다.


**Reasoning**:
The first step is to convert the 'timestamp' column to datetime objects.



In [41]:
# 1. Convert the 'timestamp' column to datetime objects
# The timestamp values appear to be in microseconds or nanoseconds since the epoch.
# Assuming microseconds based on the scale, convert to seconds for datetime conversion.
# 1. 'timestamp' 열을 datetime 객체로 변환합니다.
# 타임스탬프 값은 epoch 이후 마이크로초 또는 나노초 단위인 것으로 보입니다.
# 규모를 기준으로 마이크로초라고 가정하고 datetime 변환을 위해 초 단위로 변환합니다.
df_raw['timestamp_datetime'] = pd.to_datetime(df_raw['timestamp'], unit='us')

# Display the first few rows with the new column
# 새 열이 포함된 처음 몇 개 행을 표시합니다.
print("DataFrame with timestamp_datetime column:")
display(df_raw.head())

DataFrame with timestamp_datetime column:


user activity       timestamp         x          y         z  \
0    33  Jogging  49105962326000 -0.694638  12.680544  0.503953   
1    33  Jogging  49106062271000  5.012288  11.264028  0.953424   
2    33  Jogging  49106112167000  4.903325  10.882658 -0.081722   
3    33  Jogging  49106222305000 -0.612916  18.496431  3.023717   
4    33  Jogging  49106332290000 -1.184970  12.108489  7.205164   

       timestamp_datetime  
0 1971-07-23 08:32:42.326  
1 1971-07-23 08:34:22.271  
2 1971-07-23 08:35:12.167  
3 1971-07-23 08:37:02.305  
4 1971-07-23 08:38:52.290

**Reasoning**:
Now I will identify and handle duplicate entries in the DataFrame and check for any remaining missing values.



In [42]:
# 2. Identify and handle duplicate entries
# 2. 중복 항목 식별 및 처리
print("\nChecking for duplicate rows:")
print(f"Number of duplicate rows before dropping: {df_raw.duplicated().sum()}")

# Drop duplicate rows
# 중복 행을 삭제합니다.
df_raw.drop_duplicates(inplace=True)

print(f"Number of duplicate rows after dropping: {df_raw.duplicated().sum()}")

# 3. Handle missing values (double-check)
# 3. 누락된 값 처리 (재확인)
print("\nChecking for missing values after dropping duplicates:")
print(df_raw.isnull().sum())

# 4. Address potential semicolon issue in 'z' column (already handled in manual parsing, but verify data type)
# The manual parsing already ensured the 'z' column is float.
# We can double check the data type of 'z' column.
# 4. 'z' 열의 잠재적인 세미콜론 문제 해결 (수동 구문 분석에서 이미 처리되었지만 데이터 유형 확인)
# 수동 구문 분석을 통해 이미 'z' 열이 float인지 확인했습니다.
# 'z' 열의 데이터 유형을 다시 확인할 수 있습니다.
print("\nData type of 'z' column:")
print(df_raw['z'].dtype)


Checking for duplicate rows:
Number of duplicate rows before dropping: 66587
Number of duplicate rows after dropping: 0

Checking for missing values after dropping duplicates:
user                  0
activity              0
timestamp             0
x                     0
y                     0
z                     0
timestamp_datetime    0
dtype: int64

Data type of 'z' column:
float64


**Reasoning**:
Visualize the distribution of sensor readings (x, y, z) for each activity type to understand their characteristics and identify any potential outliers or inconsistencies using box plots.



In [43]:
# 5. Visualize the distribution of sensor readings (x, y, z) for each activity type
# 5. 각 활동 유형에 대한 센서 판독 값(x, y, z)의 분포 시각화
import matplotlib.pyplot as plt
import seaborn as sns

# Set plot style
# 플롯 스타일 설정
sns.set_style("whitegrid")

# Create box plots for x, y, and z sensor readings by activity
# 활동별 x, y, z 센서 판독 값에 대한 상자 그림 만들기
fig, axes = plt.subplots(3, 1, figsize=(12, 15))

sns.boxplot(x='activity', y='x', data=df_raw, ax=axes[0])
axes[0].set_title('Distribution of X Sensor Readings by Activity')
axes[0].set_xlabel('Activity')
axes[0].set_ylabel('X Reading')

sns.boxplot(x='activity', y='y', data=df_raw, ax=axes[1])
axes[1].set_title('Distribution of Y Sensor Readings by Activity')
axes[1].set_xlabel('Activity')
axes[1].set_ylabel('Y Reading')

sns.boxplot(x='activity', y='z', data=df_raw, ax=axes[2])
axes[2].set_title('Distribution of Z Sensor Readings by Activity')
axes[2].set_xlabel('Activity')
axes[2].set_ylabel('Z Reading')

plt.tight_layout()
plt.show()

**Reasoning**:
Prepare the time series data for CNN by creating fixed-size windows of the accelerometer data (x, y, z) along with their corresponding activity labels.



In [26]:
# 6. Prepare time series data for CNN by creating fixed-size windows
from scipy.stats import mode

def create_windows(df, window_size, overlap_size):
    """
    Create sliding windows from the time series data.

    Args:
        df (pd.DataFrame): The input DataFrame with accelerometer data and activity labels.
        window_size (int): The number of data points in each window.
        overlap_size (int): The number of overlapping data points between consecutive windows.

    Returns:
        tuple: A tuple containing two numpy arrays:
               - windows (np.ndarray): Shape (num_windows, window_size, num_features)
               - labels (np.ndarray): Shape (num_windows,)
    """
    windows = []
    labels = []
    step_size = window_size - overlap_size
    num_samples = len(df)

    for i in range(0, num_samples - window_size + 1, step_size):
        # Extract window
        window = df.iloc[i : i + window_size][['x', 'y', 'z']].values
        windows.append(window)

        # Extract label (most frequent activity in the window)
        # Use .iloc to avoid potential issues with index alignment after dropping duplicates
        window_labels = df.iloc[i : i + window_size]['activity']
        # Use mode and handle potential multiple modes by taking the first one
        label = mode(window_labels)[0][0]
        labels.append(label)

    return np.array(windows), np.array(labels)

# Define window size and overlap
window_size = 50  # Example: 50 data points per window
overlap_size = 25 # Example: 50% overlap

# Create windows and labels
import numpy as np
windows, labels = create_windows(df_raw, window_size, overlap_size)

print(f"Shape of windows: {windows.shape}")
print(f"Shape of labels: {labels.shape}")

# Display the first window and its label as an example
print("\nFirst window example:")
print(windows[0])
print(f"\nLabel of the first window: {labels[0]}")

TypeError: Argument `a` is not recognized as numeric. Support for input that cannot be coerced to a numeric array was deprecated in SciPy 1.9.0 and removed in SciPy 1.11.0. Please consider `np.unique`.

**Reasoning**:
The previous code failed because `scipy.stats.mode` does not support non-numeric data in recent versions. I will modify the code to use `pd.Series.mode()` instead, which can handle string data.



In [44]:
# 6. Prepare time series data for CNN by creating fixed-size windows
# Modified create_windows function to use pandas mode()
# 6. 고정 크기 윈도우 생성을 통해 CNN용 시계열 데이터 준비
# pandas mode()를 사용하도록 수정된 create_windows 함수
import numpy as np

def create_windows(df, window_size, overlap_size):
    """
    Create sliding windows from the time series data.

    Args:
        df (pd.DataFrame): The input DataFrame with accelerometer data and activity labels.
        window_size (int): The number of data points in each window.
        overlap_size (int): The number of overlapping data points between consecutive windows.

    Returns:
        tuple: A tuple containing two numpy arrays:
               - windows (np.ndarray): Shape (num_windows, window_size, num_features)
               - labels (np.ndarray): Shape (num_windows,)
    """
    """
    시계열 데이터에서 슬라이딩 윈도우를 생성합니다.

    인수(Args):
        df (pd.DataFrame): 가속도계 데이터 및 활동 레이블이 포함된 입력 DataFrame입니다.
        window_size (int): 각 윈도우의 데이터 포인트 수입니다.
        overlap_size (int): 연속된 윈도우 간에 겹치는 데이터 포인트 수입니다.

    반환(Returns):
        tuple: 두 개의 numpy 배열을 포함하는 튜플:
               - windows (np.ndarray): 형태 (윈도우 수, 윈도우 크기, 특징 수)
               - labels (np.ndarray): 형태 (윈도우 수,)
    """
    windows = []
    labels = []
    step_size = window_size - overlap_size
    num_samples = len(df)

    for i in range(0, num_samples - window_size + 1, step_size):
        # Extract window
        # 윈도우 추출
        window = df.iloc[i : i + window_size][['x', 'y', 'z']].values
        windows.append(window)

        # Extract label (most frequent activity in the window)
        # Use .iloc to avoid potential issues with index alignment after dropping duplicates
        # 윈도우의 레이블 추출 (윈도우에서 가장 자주 나타나는 활동)
        # 중복 제거 후 인덱스 정렬 문제 방지를 위해 .iloc 사용
        window_labels = df.iloc[i : i + window_size]['activity']
        # Use pandas mode() and take the first mode if multiple exist
        # pandas mode()를 사용하고 여러 개 있는 경우 첫 번째 mode를 가져옵니다.
        label = window_labels.mode()[0]
        labels.append(label)

    return np.array(windows), np.array(labels)

# Define window size and overlap
# 윈도우 크기 및 겹침 정의
window_size = 50  # Example: 50 data points per window # 예시: 윈도우당 50개 데이터 포인트
overlap_size = 25 # Example: 50% overlap # 예시: 50% 겹침

# Create windows and labels
# 윈도우 및 레이블 생성
windows, labels = create_windows(df_raw, window_size, overlap_size)

print(f"Shape of windows: {windows.shape}")
print(f"Shape of labels: {labels.shape}")

# Display the first window and its label as an example
# 예시로 첫 번째 윈도우와 해당 레이블을 표시합니다.
print("\nFirst window example:")
print(windows[0])
print(f"\nLabel of the first window: {labels[0]}")

Shape of windows: (40794, 50, 3)
Shape of labels: (40794,)

First window example:
[[ -0.6946377   12.680544     0.50395286]
 [  5.012288    11.264028     0.95342433]
 [  4.903325    10.882658    -0.08172209]
 [ -0.61291564  18.496431     3.0237172 ]
 [ -1.1849703   12.108489     7.205164  ]
 [  1.3756552   -2.4925237   -6.510526  ]
 [ -0.61291564  10.56939      5.706926  ]
 [ -0.50395286  13.947236     7.0553403 ]
 [ -8.430995    11.413852     5.134871  ]
 [  0.95342433   1.3756552    1.6480621 ]
 [ -8.19945     19.57244      2.7240696 ]
 [  1.4165162    5.7886477    2.982856  ]
 [ -1.879608    -2.982856    -0.29964766]
 [ -6.1291566    6.851035    -8.158588  ]
 [  5.829509    18.0061       8.539958  ]
 [  6.2789803    2.982856     2.9147544 ]
 [ -1.56634      8.308413    -1.4573772 ]
 [  3.5276701   13.593107     9.425281  ]
 [ -2.0294318   -5.706926   -10.18802   ]
 [  2.7649305   10.337844    -9.724928  ]
 [  3.568531    13.6748295    1.5390993 ]
 [ -0.50395286   3.8681788    3.7183

**Reasoning**:
Scale the numerical features (x, y, z) within each window and encode the activity labels into a numerical format for CNN input.



In [45]:
# 7. Scale the numerical features (x, y, z) within each window
# 7. 각 윈도우 내의 숫자 특징(x, y, z) 스케일링
from sklearn.preprocessing import StandardScaler

# Reshape windows for scaling (flatten the window dimension temporarily)
# 스케일링을 위해 윈도우 재구성 (윈도우 차원을 임시로 평면화)
num_windows, window_size, num_features = windows.shape
windows_reshaped = windows.reshape(-1, num_features)

# Initialize StandardScaler
# StandardScaler 초기화
scaler = StandardScaler()

# Fit and transform the reshaped data
# 재구성된 데이터 적합 및 변환
windows_scaled_reshaped = scaler.fit_transform(windows_reshaped)

# Reshape back to the original window structure
# 원래 윈도우 구조로 다시 재구성
windows_scaled = windows_scaled_reshaped.reshape(num_windows, window_size, num_features)

print(f"\nShape of scaled windows: {windows_scaled.shape}")
print("\nFirst scaled window example:")
print(windows_scaled[0])

# 8. Encode the activity labels into a numerical format
# 8. 활동 레이블을 숫자 형식으로 인코딩
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
# LabelEncoder 초기화
label_encoder = LabelEncoder()

# Fit and transform the labels
# 레이블 적합 및 변환
labels_encoded = label_encoder.fit_transform(labels)

print(f"\nShape of encoded labels: {labels_encoded.shape}")
print("\nFirst 10 encoded labels:")
print(labels_encoded[:10])
print("\nMapping of activities to encoded labels:")
# 활동과 인코딩된 레이블 매핑 출력
for i, activity in enumerate(label_encoder.classes_):
    print(f"{activity}: {i}")


Shape of scaled windows: (40794, 50, 3)

First scaled window example:
[[-0.20176185  0.79278247  0.02079662]
 [ 0.63630553  0.58018045  0.11489056]
 [ 0.62030421  0.52294139 -0.10181062]
 [-0.18976089  1.66567721  0.54829293]
 [-0.27376765  0.70692389  1.42365168]
 [ 0.1022626  -1.48451263 -1.44763899]
 [-0.18976089  0.47592363  1.11000528]
 [-0.1737596   0.98289772  1.39228706]
 [-1.33785316  0.60266723  0.99024928]
 [ 0.0402576  -0.90394547  0.26030847]
 [-1.30385056  1.82717323  0.48556365]
 [ 0.10826307 -0.24160833  0.5397389 ]
 [-0.37577585 -1.55810562 -0.14743193]
 [-0.99982604 -0.08215677 -1.79265007]
 [ 0.75631519  1.59208442  1.70308213]
 [ 0.82232048 -0.66272394  0.52548228]
 [-0.32977215  0.13657816 -0.38979509]
 [ 0.418288    0.92974721  1.88841876]
 [-0.39777761 -1.96695579 -2.21749849]
 [ 0.30627897  0.44117136 -2.12055318]
 [ 0.42428846  0.94201278  0.23749781]
 [-0.1737596  -0.52984763  0.69371085]
 [-0.43778085 -0.85692772 -0.06759465]
 [-0.62379577  1.82717323  1.278

## 데이터 분할

### Subtask:
데이터를 훈련, 검증 및 테스트 세트로 분할합니다.


**Reasoning**:
Split the scaled windows and encoded labels into training, validation, and testing sets and print their shapes.



In [46]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets (80% train, 20% test)
# 데이터를 훈련 및 테스트 세트로 분할합니다 (80% 훈련, 20% 테스트).
X_train, X_test, y_train, y_test = train_test_split(
    windows_scaled, labels_encoded, test_size=0.2, random_state=42
)

# Further split the training set into training and validation sets (80% of 80% = 64% train, 20% validation)
# 훈련 세트를 다시 훈련 및 검증 세트로 분할합니다 (80%의 80% = 64% 훈련, 20% 검증).
X_train, X_val, y_train, y_val = train_test_split(
    X_train, y_train, test_size=0.25, random_state=42
)

# Print the shapes of the resulting sets
# 결과 세트의 형태를 출력합니다.
print("Shape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_val:", X_val.shape)
print("Shape of y_val:", y_val.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (24476, 50, 3)
Shape of y_train: (24476,)
Shape of X_val: (8159, 50, 3)
Shape of y_val: (8159,)
Shape of X_test: (8159, 50, 3)
Shape of y_test: (8159,)


## CNN 모델 구축

### Subtask:
활동 인식을 위한 CNN 모델을 정의하고 구축합니다.


**Reasoning**:
Import the necessary Keras layers and define the CNN model architecture based on the instructions.



In [47]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout

# Get input shape from the training data
# 훈련 데이터에서 입력 형태를 가져옵니다.
input_shape = X_train.shape[1:]
# Get the number of output classes from the label encoder
# 레이블 인코더에서 출력 클래스 수를 가져옵니다.
num_classes = len(label_encoder.classes_)

# Define the CNN model
# CNN 모델을 정의합니다.
model = Sequential()

# Add a Conv1D layer
# Conv1D 레이어를 추가합니다.
model.add(Conv1D(filters=64, kernel_size=5, activation='relu', input_shape=input_shape))
# Add a MaxPooling1D layer
# MaxPooling1D 레이어를 추가합니다.
model.add(MaxPooling1D(pool_size=2))

# Optional: Add more Conv1D and MaxPooling1D layers
# 선택 사항: Conv1D 및 MaxPooling1D 레이어 추가
model.add(Conv1D(filters=128, kernel_size=5, activation='relu'))
model.add(MaxPooling1D(pool_size=2))

# Add a Flatten layer
# Flatten 레이어를 추가합니다.
model.add(Flatten())

# Add Dense layers
# Dense 레이어를 추가합니다.
model.add(Dense(units=100, activation='relu'))
# Add a Dropout layer for regularization (optional but recommended)
# 정규화를 위한 Dropout 레이어 추가 (선택 사항이지만 권장)
model.add(Dropout(0.5))

# Add the output Dense layer
# 출력 Dense 레이어를 추가합니다.
model.add(Dense(units=num_classes, activation='softmax'))

# Print the model summary
# 모델 요약 출력
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_2 (Conv1D)               │ (None, 46, 64)         │         1,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 23, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_3 (Conv1D)               │ (None, 19, 128)        │        41,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 9, 128)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 1152)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 100)            │       115,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 6)              │           606 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 158,018 (617.26 KB)

 Trainable params: 158,018 (617.26 KB)

 Non-trainable params: 0 (0.00 B)

## 모델 컴파일

### Subtask:
손실 함수, 옵티마이저 및 평가 메트릭을 사용하여 모델을 컴파일합니다.


**Reasoning**:
Compile the CNN model with the specified loss function, optimizer, and metrics.



In [48]:
# Compile the model
# 모델을 컴파일합니다.
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy', # Use sparse_categorical_crossentropy for integer labels # 정수 레이블에 대해 sparse_categorical_crossentropy 사용
              metrics=['accuracy']) # 평가 지표: 정확도

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_2 (Conv1D)               │ (None, 46, 64)         │         1,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 23, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_3 (Conv1D)               │ (None, 19, 128)        │        41,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 9, 128)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 1152)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 100)            │       115,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 6)              │           606 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 158,018 (617.26 KB)

 Trainable params: 158,018 (617.26 KB)

 Non-trainable params: 0 (0.00 B)

## 모델 훈련

### Subtask:
훈련 데이터를 사용하여 CNN 모델을 훈련합니다.


**Reasoning**:
Train the compiled CNN model using the training data and validate it using the validation data, storing the training history.



In [49]:
# Define the number of epochs and batch size
# 에포크 수와 배치 크기를 정의합니다.
epochs = 10
batch_size = 64

# Train the model
# 모델을 훈련합니다.
history = model.fit(
    X_train,
    y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_data=(X_val, y_val)
)

# Print training and validation accuracy and loss from the history
# 기록에서 훈련 및 검증 정확도와 손실을 출력합니다.
print("\nTraining History:")
print("Epoch | Train Loss | Train Acc | Val Loss | Val Acc")
print("---------------------------------------------------")
for epoch in range(epochs):
    print(
        f"{epoch + 1:<5} | "
        f"{history.history['loss'][epoch]:<10.4f} | "
        f"{history.history['accuracy'][epoch]:<9.4f} | "
        f"{history.history['val_loss'][epoch]:<9.4f} | "
        f"{history.history['val_accuracy'][epoch]:<8.4f}"
    )

Epoch 1/10
383/383 ━━━━━━━━━━━━━━━━━━━━ 11s 25ms/step - accuracy: 0.7072 - loss: 0.7881 - val_accuracy: 0.9017 - val_loss: 0.2738
Epoch 2/10
383/383 ━━━━━━━━━━━━━━━━━━━━ 8s 22ms/step - accuracy: 0.8941 - loss: 0.3046 - val_accuracy: 0.9417 - val_loss: 0.1737
Epoch 3/10
383/383 ━━━━━━━━━━━━━━━━━━━━ 9s 24ms/step - accuracy: 0.9381 - loss: 0.1907 - val_accuracy: 0.9587 - val_loss: 0.1356
Epoch 4/10
383/383 ━━━━━━━━━━━━━━━━━━━━ 10s 23ms/step - accuracy: 0.9541 - loss: 0.1383 - val_accuracy: 0.9643 - val_loss: 0.1132
Epoch 5/10
383/383 ━━━━━━━━━━━━━━━━━━━━ 8s 21ms/step - accuracy: 0.9649 - loss: 0.1132 - val_accuracy: 0.9646 - val_loss: 0.1259
Epoch 6/10
383/383 ━━━━━━━━━━━━━━━━━━━━ 10s 26ms/step - accuracy: 0.9714 - loss: 0.0930 - val_accuracy: 0.9560 - val_loss: 0.1462
Epoch 7/10
383/383 ━━━━━━━━━━━━━━━━━━━━ 8s 20ms/step - accuracy: 0.9735 - loss: 0.0855 - val_accuracy: 0.9646 - val_loss: 0.1094
Epoch 8/10
383/383 ━━━━━━━━━━━━━━━━━━━━ 10s 25ms/step - accuracy: 0.9757 - loss: 0.0729 - val_

## 모델 평가

### Subtask:
테스트 데이터에서 훈련된 모델의 성능을 평가합니다.

**Reasoning**:
Evaluate the trained CNN model on the test data to assess its performance on unseen data and print the evaluation results (loss and accuracy).

In [50]:
# Evaluate the model on the test data
# 테스트 데이터에서 모델을 평가합니다.
loss, accuracy = model.evaluate(X_test, y_test, verbose=1)

# Print the evaluation results
# 평가 결과를 출력합니다.
print(f"\nTest Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

255/255 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9614 - loss: 0.1335

Test Loss: 0.1257
Test Accuracy: 0.9645
